### ISSUE TITLE
View Code on GitHub goes to laravel repo

### ISSUE THREAD

**Issue by dprothero** [TwilioDevEd/server-notifications-node#1]
When you click on the View Code on GitHub link in the right column of the code editor, it goes to the wrong repo...

![image](https://cloud.githubusercontent.com/assets/1897006/14538931/ef5ff4ae-0232-11e6-9105-c6ee274bf53a.png)

**Comment by shyba** [comment]
Thank you David,
we will fix the link as soon as possible!

**Comment by shyba** [comment]
https://github.com/TwilioDevEd/server-notifications-node/commit/a8b84a15c1ffd0ba85beac318f9a31ac0bbc2b10 fixes it.
Thank you a lot for finding this issue! :+1:
