### ISSUE TITLE
404 on "SMS and MMS Marketing Notifications" link

### ISSUE THREAD

**Issue by humphd** [TwilioDevEd/server-notifications-node#10]
<img width="790" alt="screen shot 2017-05-29 at 7 45 22 pm" src="https://cloud.githubusercontent.com/assets/427398/26563871/56144ce2-44a7-11e7-91fc-f1887855b138.png">

I'm not sure where this code lives, so I've filed it here.  The link at the end of the associated tutorial for this repo has a link for `SMS and MMS Marketing Notifications` which points to https://www.twilio.com/howto/walkthrough/marketing-notifications/node/express and is 404.

**Comment by smendes** [comment]
Thank you for your report, the link wasn't updated properly. It's fixed now.
