### ISSUE TITLE
404 link on E.164 link

### ISSUE THREAD

**Issue by humphd** [TwilioDevEd/server-notifications-node#9]
In the README, there's a link for `E.164 format` which points to https://www.twilio.com/help/faq/phone-numbers/how-do-i-format-phone-numbers-to-work-internationally.  That page is 404 for me, but the following appears in the list of suggestions: 

https://support.twilio.com/hc/en-us/articles/223179888-How-do-I-dial-international-numbers-with-Twilio-

**Comment by smendes** [comment]
Indeed the link was moved, all good now thanks to you.
